session_name: General
windows:
    - window_name: Main
      panes:
          - null
    - window_name: Reddit
      panes:
          - tuir
    - window_name: RSS Feeds
      panes:
          - newsboat
    - window_name: IRC
      panes:
          - weechat
    - window_name: Music
      panes:
          - vimpc
