#!/bin/sh

# if [ "$UUID" != 0 ]; then
#     echo "Please run script as root."
#     exit 1
# fi

cd "$(dirname "$(readlink -f "${0}")")" || exit 1
name="${1}.nix"

test -f "${name}" || exit 2
mv /etc/nixos/configuration.nix /etc/nixos/.old-config.nix
ln -s "$(dirname "$(readlink -f humboldt.nix)")" /etc/nixos/per-machine
echo "# This file only import the generated hardware configurations,
# and the specific configuration for this machine.

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix

      ./per-machine/${name}
    ];
}" > /etc/nixos/configuration.nix

