# bash_profile: bash init file for bash login shells.

# If present, load zsh's environment variables.
# test -f "$HOME/.zshenv" && source "$HOME/.zshenv"

# If there is a nix store, initalize it.
if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
    source "$HOME/.nix-profile/etc/profile.d/nix.sh"
fi

# If tmux exists, and the shell is not currently within a tmux session,
# then attach to the server or create a new session
if command -v tmux > /dev/null && [ -z "$TMUX" ] && [ "$(tty)" = "/dev/tty1" ]; then
    tmux attach || tmux new-session -s winterm
fi
