#!/usr/bin/env zsh
# zprofile: init file for zsh login shells

# Set language
export LANG="en_CA.UTF-8"

# Add local bin directory to path.
export PATH="$HOME/.local/bin:$PATH"

# If there is a nix store, initalize it.
# Load the paths from the nix-profile.
if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
    source "$HOME/.nix-profile/etc/profile.d/nix.sh"
    export FPATH="$HOME/.nix-profile/share/zsh/site-functions:$FPATH"
fi

# If tmux exists, and the shell is not currently within a tmux session,
# then attach to the server or create a new session
if command -v tmux > /dev/null && [ -z "$TMUX" ] && [ "$(tty)" = "/dev/tty1" ] ; then
    tmux attach || tmux new-session -s winterm
fi
