session_name: general
windows:
    - window_name: Main
      panes:
          - neofetch
    - window_name: Email
      panes:
          - mbsync -aV ; neomutt -v
    - window_name: Calendar
      panes:
          - calcurse --version
          - task --version ; vit --version
    - window_name: Music
      panes:
          - vimpc --version
    - window_name: Reddit
      panes:
          - tuir --version
    - window_name: RSS Feeds
      panes:
          - newsboat --version
    - window_name: IRC
      panes:
          - weechat --version
