"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                                                                             "
" VIMRC                                                                       "
" This file is for loading vim with my prefered settings, but without plugins."
" For situtations where I've only have access to vanilla vim.                 "
"                                                                             "
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set nocompatible                        " Do not emulate the original ex/vi
syntax on                               " Enable syntax highlight
filetype plugin indent on               " Load filetype detection and indenting

set ruler                               " Enable ruler at the bottom by default.
set incsearch                           " Display incremental results of searches
set hlsearch                            " Highlight search matches
set backspace=indent,eol,start          " Backspace will delete almost everything
set listchars="tab:> ,trail:-,nbsp:+"   " Show non-printing characters as such
set showcmd                             " Show the incremental results of commands
set ttyfast                             " Assume that I am using a fast terminal
set smarttab                            " Tab smartly
set encoding=utf-8                      " Encode everything in UTF-8
set display="lastline,msgsep"           " Show results of last line

set backupdir=~/.cache/vim//,.          " Set backup directory to cache directory.
set directory=~/.cache/vim//,.          " Put swap files in a seperate directory.

colorscheme slate                       " Use this colorscheme instead

" Set the statusline to the following:
set statusline=%1*[%n]
set statusline+=\ %f
set statusline+=\ %m
set statusline+=%=
set statusline+=%2*[%{&fileformat}\ %{&fileencoding?&fileencoding:&encoding}]
set statusline+=\ %y%*
set statusline+=\ {%B}
set statusline+=\ %l:%c/%L
set statusline+=\ %P

" Some remappin that are useful, but handled with plugins in my neovim config.

" Align Y with D, C, etc.
nnoremap Y y$

" Navigational shortcuts for moving between buffers.
nnoremap <silent> [b :bprevious<CR>
nnoremap <silent> ]b :bnext<CR>
nnoremap <silent> [B :bfirst<CR>
nnoremap <silent> ]B :blast<CR>

" Insert a blank line above or below the current line.
nnoremap <leader>o m`A<CR><ESC>``
nnoremap <leader>O m`ko<ESC>``

" Move lines in normal and visual mode
nnoremap <silent> <leader>j :move .+1<CR>==
nnoremap <silent> <leader>k :move .-2<CR>==
vnoremap <silent> <C-j> :move '>+1<CR>gv=gv
vnoremap <silent> <C-k> :move '<-2<CR>gv=gv

" Source the common configuration file.
source $HOME/.vim/common.vim
