#!/bin/sh

relocate() {
    cd "$(dirname "${file}")" || exit 1

    old_prefix="${file%%.*}"
    ext="${file##*.}"
    next_prefix="$(find . -maxdepth 1 | rofi -dmenu -p "Enter new name")"

    if test -n "$next_prefix" ; then
        if test -e "${next_prefix}.${ext}"; then
            notify-desktop " sxiv" "ERROR: $old_prefix has not been renamed to $next_prefix."
        else
            "${1}" "$file" "${next_prefix}.${ext}" && \
                notify-desktop " sxiv" "$old_prefix has been renamed to $next_prefix."
        fi
    fi
}

while read -r file; do
    case "${1}" in
        # Rename a file, will fail if it cannot do so.
        "r"|"C-r") relocate "mv";;
        "c"|"C-c") relocate "cp";;
        "d"|"C-d") trash-put "$file" ;;
        "o"|"C-o") gimp "$file" & ;;
        "y"|"C-y") printf "%s\n" "$file" | xclip -selection clipboard && notify-desktop " sxiv" "$file name copied to clipboard" ;;
        "Y")
            full_path="$(readlink -f "$file")"
            printf "%s\n" "$full_path" | xclip -selection clipboard && notify-desktop " sxiv"  "$file path copied to clipboard"
            ;;
    esac
done
